server:
  port: ${PORT:8761}
  
eureka:
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: false
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
    fetch-registry: false
  instance:
    lease-renewal-interval-in-seconds: 10
  server:
    wait-time-in-ms-when-sync-empty: 0

logging:
  level:
    com: INFO
    org: INFO

management:
  security:
    enabled: false
    
spring:
  boot:
    admin:
      context-path: /admin