server:
  port: 7777
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 1000

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

logging:
  level:
    com: INFO
    org: INFO

management:
  security:
    enabled: false 
    
spring:
  boot:
    admin:
      url:
      - http://localhost:8761/admin
