spring:
  profiles:
    active:
    - development
  cloud:
    config:
      uri: http://localhost:8888

server:
  port: 8010

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
      
logging:
  level:
    com: INFO
    org: INFO

management:
  security:
    enabled: false 
